### PR TITLE
Fixes #49: File permissions checks on contributed modules

### LINKED ISSUE #49: Shell script permissions checks fail on CircleCI
To reproduce: composer require a contributed module (for example [password_policy](https://www.drupal.org/project/password_policy) that has .sh test files and push to CircleCI, validation fails .

```
GrumPHP is sniffing your code!
Running task 1/8: EcsTask... ✔
Running task 2/8: PhpcsTask... ✔
Running task 3/8: PhpCompatibilityTask... ✔
Running task 4/8: PhpCheckSyntaxTask... ✔
Running task 5/8: CheckFilePermissionsTask... ✘
Aborted ...
Fix file permissions for the following shell scripts:
File: ./web/modules/contrib/password_policy/tests/drupal_ti/before/before_script.sh
Current permissions:  644
Expected permissions: 755
-
To skip commit checks, add -n or --no-verify flag to commit command
Exited with code exit status 1 
CircleCI received exit code 1 
```

Problematic function at https://github.com/wunderio/code-quality/blob/master/bin/check_perms#L63-L84 - I'd suggest a fix to ignoring the permission checking for files in `./web/modules/contrib`

### PR DESCRIPTION
**Pull request by kirkkala**
See issue #49

### CODE REVIEW

File: src/Task/tasks.yml [hunk 1]
```diff
@@ -30,6 +30,7 @@ Wunderio\GrumPHP\Task\CheckFilePermissions\CheckFilePermissionsTask:
         - '/node_modules/'
         - '/core/'
         - '/libraries/'
+        - '/web/modules/contrib/'
```
Comment (guncha25) [inline src/Task/tasks.yml]: This assumes that there is web. Should we just say modules/contib?

Comment (kirkkala) [reply src/Task/tasks.yml]: Thanks, yes, it was a bad assumption. 70acc03 fixes.

**Review by guncha25 — APPROVED** [review]
